# This is a basic workflow to help you get started with Actions

name: Continuous

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: 
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: MooseIDE
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ "Pharo64-11" ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Coverage
          path: ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
